import { relative } from 'path';
import { writeFileSync } from 'fs';
import type { ScanSummary } from '@guardrail/core';

export function generateHtmlReport(
  summary: ScanSummary,
  cwd: string,
  outputPath: string,
): void {
  const resultsWithIssues = summary.results.filter(
    (r) => r.violations.length > 0,
  );

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Guardrail Report</title>
<style>
  :root { --bg: #0a0a0a; --surface: #141414; --border: #262626; --text: #fafafa; --text-dim: #a1a1aa; --red: #ef4444; --yellow: #eab308; --blue: #3b82f6; --green: #22c55e; --orange: #f97316; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, monospace; background: var(--bg); color: var(--text); padding: 2rem; max-width: 1200px; margin: 0 auto; }
  h1 { font-size: 1.5rem; font-weight: 600; margin-bottom: 0.25rem; }
  .subtitle { color: var(--text-dim); margin-bottom: 2rem; font-size: 0.875rem; }
  .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
  .card { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; }
  .card .value { font-size: 1.75rem; font-weight: 700; }
  .card .label { color: var(--text-dim); font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; margin-top: 0.25rem; }
  .card.critical .value { color: var(--red); }
  .card.high .value { color: var(--orange); }
  .card.warning .value { color: var(--yellow); }
  .card.info .value { color: var(--blue); }
  .card.clean .value { color: var(--green); }
  .file { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; margin-bottom: 1rem; overflow: hidden; }
  .file-header { padding: 0.75rem 1rem; border-bottom: 1px solid var(--border); font-weight: 500; font-size: 0.875rem; display: flex; justify-content: space-between; }
  .file-count { color: var(--text-dim); }
  .violation { padding: 0.5rem 1rem; border-bottom: 1px solid var(--border); font-size: 0.8125rem; display: flex; gap: 0.75rem; align-items: baseline; }
  .violation:last-child { border-bottom: none; }
  .badge { padding: 0.125rem 0.5rem; border-radius: 4px; font-size: 0.6875rem; font-weight: 600; white-space: nowrap; }
  .badge.critical { background: #7f1d1d; color: #fca5a5; }
  .badge.high { background: #7c2d12; color: #fdba74; }
  .badge.warning { background: #713f12; color: #fde047; }
  .badge.info { background: #1e3a5f; color: #93c5fd; }
  .loc { color: var(--text-dim); white-space: nowrap; font-family: monospace; font-size: 0.75rem; }
  .msg { flex: 1; }
  .rule-id { color: var(--text-dim); font-size: 0.75rem; white-space: nowrap; }
  .fixable { color: var(--green); font-size: 0.6875rem; }
  .footer { margin-top: 2rem; color: var(--text-dim); font-size: 0.75rem; text-align: center; }
</style>
</head>
<body>
<h1>Guardrail Report</h1>
<p class="subtitle">${summary.totalFiles} files scanned &middot; ${new Date().toLocaleString()}</p>

<div class="summary">
  <div class="card ${summary.totalViolations === 0 ? 'clean' : ''}">
    <div class="value">${summary.totalViolations}</div>
    <div class="label">Total Issues</div>
  </div>
  <div class="card critical">
    <div class="value">${summary.bySeverity.critical}</div>
    <div class="label">Critical</div>
  </div>
  <div class="card high">
    <div class="value">${summary.bySeverity.high}</div>
    <div class="label">High</div>
  </div>
  <div class="card warning">
    <div class="value">${summary.bySeverity.warning}</div>
    <div class="label">Warning</div>
  </div>
  <div class="card info">
    <div class="value">${summary.bySeverity.info}</div>
    <div class="label">Info</div>
  </div>
</div>

${resultsWithIssues
  .map(
    (result) => `
<div class="file">
  <div class="file-header">
    <span>${relative(cwd, result.filePath)}</span>
    <span class="file-count">${result.violations.length} issues</span>
  </div>
  ${result.violations
    .map(
      (v) => `
  <div class="violation">
    <span class="badge ${v.severity}">${v.severity.toUpperCase()}</span>
    <span class="loc">${v.location.line}:${v.location.column}</span>
    <span class="msg">${escapeHtml(v.message)}</span>
    <span class="rule-id">${v.ruleId}</span>
    ${v.fix ? '<span class="fixable">fixable</span>' : ''}
  </div>`,
    )
    .join('')}
</div>`,
  )
  .join('')}

<div class="footer">Generated by Guardrail</div>
</body>
</html>`;

  writeFileSync(outputPath, html);
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
